package dev.otectus.mcaquests.compat.reputation;

import dev.otectus.mcaquests.McaQuests;
import dev.otectus.mcaquests.project.state.ProjectSavedData;
import dev.otectus.mcaquests.quest.reputation.ReputationTiers;
import dev.otectus.mcaquests.state.PlayerQuestData;
import dev.otectus.mcaquests.state.QuestAttachments;
import dev.otectus.mcaquests.state.VillageStanding;
import dev.otectus.mcareputation.api.LegacyImportProvider;
import dev.otectus.mcareputation.api.LegacyImportRequest;
import dev.otectus.mcareputation.community.CommunityKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;

import java.util.Optional;
import java.util.Set;

/**
 * Hands MCA: Reputation the standing a pre-Reputation Quests world already had (spec §32.2).
 *
 * <h2>The honest limitation</h2>
 *
 * <p>Quests' v1 reputation was keyed by <em>village</em> and shared by the whole world. It is not
 * possible to reconstruct who earned what — that information was never recorded. So this import does
 * not invent deeds. Each legacy village score becomes a non-decaying <b>baseline</b> with no incident
 * attached, which preserves the number the player used to see while making everything from that point
 * on correct and per player.
 *
 * <h2>Who is eligible</h2>
 *
 * <p>§32.2 lists the criteria, and they exist to stop a brand-new player joining an established server
 * and inheriting somebody else's reputation. A player qualifies when they have quest history, an
 * active quest, progression stats, or a Quests title — that is, when they were playing this world
 * before Reputation arrived. An administrator running {@code /mcareputation migrate run} passes
 * {@code force} and takes responsibility for the decision.
 *
 * <p>Legacy keys carry no dimension, so they are read as {@code minecraft:overworld} — the only thing
 * they could have meant in practice, since that is where MCA villages are generated by default.
 */
public final class QuestsLegacyImportProvider implements LegacyImportProvider {

    /** The marker written on success; the same string forever, since it means "v1 has been read". */
    public static final String SOURCE_ID = "mcaquests:legacy_reputation_v1";

    private static final ResourceLocation LEGACY_DIMENSION = ResourceLocation.fromNamespaceAndPath("minecraft", "overworld");

    @Override
    public String providerName() {
        return "mcaquests:legacy-reputation";
    }

    @Override
    @SuppressWarnings("deprecation") // reading the retained v1 tags is exactly this class's job
    public Optional<LegacyImportRequest> buildRequest(MinecraftServer server, ServerPlayer player,
                                                      boolean force) {
        ProjectSavedData data = ProjectSavedData.get(server);
        Set<String> legacyKeys = data.reputationKeys();
        if (legacyKeys.isEmpty()) {
            return Optional.empty();
        }
        if (!force && !isEligible(player)) {
            McaQuests.LOGGER.debug("[MCA: Quests] {} has no pre-Reputation Quests history; starting at 0 "
                    + "rather than inheriting the world's shared legacy standing",
                    player.getGameProfile().getName());
            return Optional.empty();
        }

        LegacyImportRequest.Builder request = LegacyImportRequest
                .builder(server, player.getUUID(), SOURCE_ID)
                .version("1");

        int communities = 0;
        for (String identity : legacyKeys) {
            Optional<Integer> villageId = VillageStanding.parseLegacyVillageId(identity);
            if (villageId.isEmpty()) {
                continue; // a non-village scope identity; not standing with a community
            }
            Optional<CommunityKey> community = CommunityKey.of(LEGACY_DIMENSION, villageId.get());
            if (community.isEmpty()) {
                continue;
            }
            int score = data.reputation(identity);
            if (score != 0) {
                request.baseline(community.get(), score);
                communities++;
            }
            String highWater = data.tierHighWater(identity);
            if (highWater != null && !highWater.isBlank()) {
                request.tierHighWater(community.get(), ReputationTiers.DEFAULT_ID, highWater);
            }
            dev.otectus.mcaquests.compat.McaCompat.villageName(server.overworld(), villageId.get())
                    .ifPresent(name -> request.communityName(community.get(), name));
            copyTitles(player, community.get(), request);
        }

        if (communities == 0) {
            return Optional.empty();
        }
        return Optional.of(request.build());
    }

    /** Village and global titles the player already holds, so migration does not cost them a badge. */
    private static void copyTitles(ServerPlayer player, CommunityKey community,
                                   LegacyImportRequest.Builder request) {
        QuestAttachments.get(player).ifPresent(data -> {
            data.titles().forVillage(community.villageId()).forEach(title ->
                    request.villageTitle(community, title));
            data.titles().global().forEach(request::globalTitle);
        });
    }

    /**
     * §32.2 step 4: a player inherits the legacy snapshot only if they were already playing this world.
     * Every branch is a fact Quests itself recorded, so no guesswork is involved.
     */
    private static boolean isEligible(ServerPlayer player) {
        Optional<PlayerQuestData> data = QuestAttachments.get(player);
        if (data.isEmpty()) {
            return false;
        }
        PlayerQuestData quests = data.get();
        boolean hasHistory = !quests.history().completionsView().isEmpty();
        boolean hasActive = !quests.active().isEmpty();
        boolean hasTitles = !quests.titles().isEmpty();
        boolean hasProgression = !quests.stats().isEmpty();
        // On a singleplayer world there is only ever one person the legacy numbers could have
        // described, so the eligibility question does not really arise.
        boolean singleplayer = player.server.isSingleplayer();
        return hasHistory || hasActive || hasTitles || hasProgression || singleplayer;
    }
}
