package dev.otectus.mcaquests.compat.reputation;

import dev.otectus.mcaquests.McaQuests;
import dev.otectus.mcaquests.project.state.ProjectSavedData;
import dev.otectus.mcaquests.quest.reputation.ReputationTiers;
import dev.otectus.mcaquests.state.PlayerQuestData;
import dev.otectus.mcaquests.state.QuestCapabilities;
import dev.otectus.mcaquests.state.VillageStanding;
import dev.otectus.mcareputation.api.LegacyImportProvider;
import dev.otectus.mcareputation.api.LegacyImportRequest;
import dev.otectus.mcareputation.api.McaReputationApi;
import dev.otectus.mcareputation.community.CommunityKey;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Hands MCA: Reputation the standing a pre-Reputation Quests world already had (spec §32.2).
 *
 * <h2>The honest limitation</h2>
 *
 * <p>Quests' v1 reputation was keyed by <em>village</em> and shared by the whole world. It is not
 * possible to reconstruct who earned what — that information was never recorded. So this import does
 * not invent deeds. Each legacy village score becomes a non-decaying <b>baseline</b> with no incident
 * attached, which preserves the number the player used to see while making everything from that point
 * on correct and per player.
 *
 * <p>Current Quests saves already have a per-player, dimension-aware v2 snapshot. That snapshot takes
 * precedence over the retained v1 tags. Communities already present in Reputation are excluded because
 * the Quests snapshot can be their fallback mirror; importing it again would double their score.
 *
 * <h2>Who is eligible</h2>
 *
 * <p>§32.2 lists the criteria, and they exist to stop a brand-new player joining an established server
 * and inheriting somebody else's reputation. A player qualifies when they have quest history, an
 * active quest, progression stats, or a Quests title — that is, when they were playing this world
 * before Reputation arrived. An administrator running {@code /mcareputation migrate run} passes
 * {@code force} and takes responsibility for the decision.
 *
 * <p>Legacy keys carry no dimension, so they are read as {@code minecraft:overworld} — the only thing
 * they could have meant in practice, since that is where MCA villages are generated by default.
 */
public final class QuestsLegacyImportProvider implements LegacyImportProvider {

    /** Stable across snapshot versions so an existing successful import is never replayed. */
    public static final String SOURCE_ID = "mcaquests:legacy_reputation_v1";

    @Override
    public String providerName() {
        return "mcaquests:legacy-reputation";
    }

    @Override
    @SuppressWarnings("deprecation") // reading the retained v1 tags is exactly this class's job
    public Optional<LegacyImportRequest> buildRequest(MinecraftServer server, ServerPlayer player,
                                                      boolean force) {
        ProjectSavedData data = ProjectSavedData.get(server);
        boolean eligible = force || isEligible(player);
        boolean hasCurrent = !data.standing().communities(player.getUUID()).isEmpty();
        if (!hasCurrent && !eligible) {
            McaQuests.LOGGER.debug("[MCA: Quests] {} has no pre-Reputation Quests history; starting at 0 "
                    + "rather than inheriting the world's shared legacy standing",
                    player.getGameProfile().getName());
            return Optional.empty();
        }

        LegacyImportRequest.Builder request = LegacyImportRequest
                .builder(server, player.getUUID(), SOURCE_ID)
                .version(hasCurrent ? "2" : "1");

        Map<String, Integer> sharedScores = new LinkedHashMap<>();
        Map<String, String> sharedHighWater = new LinkedHashMap<>();
        for (String identity : data.reputationKeys()) {
            sharedScores.put(identity, data.reputation(identity));
            sharedHighWater.put(identity, data.tierHighWater(identity));
        }
        Set<String> canonical = McaReputationApi.knownCommunities(server, player.getUUID()).stream()
                .map(CommunityKey::asString).collect(Collectors.toSet());
        var selected = QuestsStandingImport.select(data.standing(), player.getUUID(), sharedScores,
                sharedHighWater, eligible, canonical);
        for (var entry : selected.entrySet()) {
            var identity = entry.getKey();
            var snapshot = entry.getValue();
            CommunityKey community = new CommunityKey(identity.dimension(), identity.villageId());
            // Keep zero-score communities too: they can carry earned titles and a previous best tier.
            request.baseline(community, snapshot.score());
            snapshot.highWater().ifPresent(tier ->
                    request.tierHighWater(community, ReputationTiers.DEFAULT_ID, tier));
            snapshot.titles().forEach(title -> request.villageTitle(community, title));
            ServerLevel level = server.getLevel(ResourceKey.create(Registries.DIMENSION, identity.dimension()));
            if (level != null) {
                dev.otectus.mcaquests.compat.McaCompat.villageName(level, identity.villageId())
                        .ifPresent(name -> request.communityName(community, name));
            }
            copyTitles(player, community, request);
        }
        QuestCapabilities.get(player).ifPresent(quests -> quests.titles().global().forEach(request::globalTitle));
        LegacyImportRequest built = request.build();
        return built.hasAnything() ? Optional.of(built) : Optional.empty();
    }

    /** Village and global titles the player already holds, so migration does not cost them a badge. */
    private static void copyTitles(ServerPlayer player, CommunityKey community,
                                   LegacyImportRequest.Builder request) {
        QuestCapabilities.get(player).ifPresent(data -> {
            data.titles().forVillage(community.dimension(), community.villageId()).forEach(title ->
                    request.villageTitle(community, title));
            data.titles().global().forEach(request::globalTitle);
        });
    }

    /**
     * §32.2 step 4: a player inherits the legacy snapshot only if they were already playing this world.
     * Every branch is a fact Quests itself recorded, so no guesswork is involved.
     */
    private static boolean isEligible(ServerPlayer player) {
        Optional<PlayerQuestData> data = QuestCapabilities.get(player);
        if (data.isEmpty()) {
            return false;
        }
        PlayerQuestData quests = data.get();
        boolean hasHistory = !quests.history().completionsView().isEmpty();
        boolean hasActive = !quests.active().isEmpty();
        boolean hasTitles = !quests.titles().isEmpty();
        boolean hasProgression = !quests.stats().isEmpty();
        // On a singleplayer world there is only ever one person the legacy numbers could have
        // described, so the eligibility question does not really arise.
        boolean singleplayer = player.server.isSingleplayer();
        return hasHistory || hasActive || hasTitles || hasProgression || singleplayer;
    }
}
