package dev.otectus.mcaquests.client.gui;

import com.mojang.math.Divisor;
import dev.otectus.mcaquests.McaQuests;
import it.unimi.dsi.fastutil.ints.IntIterator;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/**
 * Every sprite on the mod's two GUI sheets, named once.
 *
 * <p>Until this class the mod shipped <b>no textures at all</b>: every panel, card, bar and scrollbar
 * was a solid {@code fill()} rectangle, and the interface read as a debug overlay rather than as part
 * of the game. The sheets are generated by {@code tools/gen_gui_textures.py}, which also writes
 * {@code gui_layout.json} beside them; {@code GuiTexturesExistTest} asserts that every constant here
 * agrees with that file, so a UV cannot be moved in the generator without the code that blits it
 * being updated too.
 *
 * <p>Both sheets are 256×256 because that is the size the nine-slice below assumes, as vanilla's
 * own {@code blitRepeating} overload did before 1.20.2 removed the raw-texture nine-slice from
 * {@code GuiGraphics} in favour of GUI-atlas sprite metadata. The middle band of every nine-sliced
 * sprite is a flat colour, so stretching a panel to any size never shows a seam.
 *
 * <p>This package deliberately knows nothing about quests. It is chrome, and the screens are written
 * against it.
 */
public final class GuiTextures {

    /** Panels, frames, buttons, bars and the scrollbar. */
    public static final ResourceLocation PANEL_SHEET =
            ResourceLocation.fromNamespaceAndPath(McaQuests.MOD_ID, "textures/gui/panel.png");

    /** 16×16 glyphs: quest kinds, objective states, hearts, difficulty pips, professions. */
    public static final ResourceLocation ICON_SHEET =
            ResourceLocation.fromNamespaceAndPath(McaQuests.MOD_ID, "textures/gui/icons.png");

    /** Both sheets are square and this size. See the class note on {@code blitRepeating}. */
    public static final int SHEET = 256;

    private GuiTextures() {
    }

    /**
     * One rectangle on one sheet, plus the nine-slice insets it was drawn to survive.
     *
     * <p>The two insets are independent because the sprites are: a divider is 48x3 and only ever
     * tiles sideways, a scrollbar track is 6x32 and only ever tiles downward, and one figure could
     * describe neither without consuming the whole sprite.
     *
     * @param sliceX pixels of border preserved on the left and right when stretched, or {@code 0} for
     *               a sprite only ever blitted at its natural size
     * @param sliceY the same for the top and bottom
     */
    public record Sprite(ResourceLocation sheet, int u, int v, int width, int height,
                         int sliceX, int sliceY) {

        private static Sprite panel(int u, int v, int width, int height, int sliceX, int sliceY) {
            return new Sprite(PANEL_SHEET, u, v, width, height, sliceX, sliceY);
        }

        private static Sprite icon(int column, int row) {
            return new Sprite(ICON_SHEET, column * 16, row * 16, 16, 16, 0, 0);
        }

        /** Draws the sprite at its natural size. */
        public void blit(GuiGraphics graphics, int x, int y) {
            graphics.blit(sheet, x, y, u, v, width, height);
        }

        /**
         * Draws the sprite stretched to {@code w}×{@code h}, keeping its borders intact and tiling
         * the middle. Falls back to a plain blit for a sprite with no slice, which would otherwise
         * be smeared.
         */
        public void nineSlice(GuiGraphics graphics, int x, int y, int w, int h) {
            if (sliceX <= 0 && sliceY <= 0) {
                graphics.blit(sheet, x, y, u, v, Math.min(w, width), Math.min(h, height));
                return;
            }
            blitNineSliced(graphics, sheet, x, y, Math.max(1, w), Math.max(1, h), sliceX, sliceY,
                    width, height, u, v);
        }
    }

    /**
     * Vanilla's pre-1.20.2 {@code GuiGraphics.blitNineSliced}, reimplemented over the blit overloads
     * that survive.
     *
     * <p>1.20.2 moved nine-slicing onto the GUI sprite atlas: {@code blitSprite} reads the borders
     * from a sprite's {@code .mcmeta}, and the raw-{@code ResourceLocation} form the mod's own two
     * sheets need was deleted. These sheets are ordinary textures rather than atlas sprites, so the
     * geometry is done here instead — same corners at natural size, same tiled (never stretched)
     * edges and centre, same clamping of the insets to half the drawn size.
     */
    private static void blitNineSliced(GuiGraphics graphics, ResourceLocation sheet, int x, int y,
                                       int w, int h, int sliceX, int sliceY,
                                       int spriteW, int spriteH, int u, int v) {
        int left = Math.min(sliceX, w / 2);
        int right = Math.min(sliceX, w / 2);
        int top = Math.min(sliceY, h / 2);
        int bottom = Math.min(sliceY, h / 2);
        if (w == spriteW && h == spriteH) {
            graphics.blit(sheet, x, y, u, v, w, h);
            return;
        }
        if (h == spriteH) {
            graphics.blit(sheet, x, y, u, v, left, h);
            repeat(graphics, sheet, x + left, y, w - right - left, h,
                    u + left, v, spriteW - right - left, spriteH);
            graphics.blit(sheet, x + w - right, y, u + spriteW - right, v, right, h);
            return;
        }
        if (w == spriteW) {
            graphics.blit(sheet, x, y, u, v, w, top);
            repeat(graphics, sheet, x, y + top, w, h - bottom - top,
                    u, v + top, spriteW, spriteH - bottom - top);
            graphics.blit(sheet, x, y + h - bottom, u, v + spriteH - bottom, w, bottom);
            return;
        }
        graphics.blit(sheet, x, y, u, v, left, top);
        repeat(graphics, sheet, x + left, y, w - right - left, top,
                u + left, v, spriteW - right - left, top);
        graphics.blit(sheet, x + w - right, y, u + spriteW - right, v, right, top);
        graphics.blit(sheet, x, y + h - bottom, u, v + spriteH - bottom, left, bottom);
        repeat(graphics, sheet, x + left, y + h - bottom, w - right - left, bottom,
                u + left, v + spriteH - bottom, spriteW - right - left, bottom);
        graphics.blit(sheet, x + w - right, y + h - bottom, u + spriteW - right,
                v + spriteH - bottom, right, bottom);
        repeat(graphics, sheet, x, y + top, left, h - bottom - top,
                u, v + top, left, spriteH - bottom - top);
        repeat(graphics, sheet, x + left, y + top, w - right - left, h - bottom - top,
                u + left, v + top, spriteW - right - left, spriteH - bottom - top);
        repeat(graphics, sheet, x + w - right, y + top, right, h - bottom - top,
                u + spriteW - right, v + top, right, spriteH - bottom - top);
    }

    /** Vanilla's pre-1.20.2 {@code blitRepeating}: tile a source band rather than stretch it. */
    private static void repeat(GuiGraphics graphics, ResourceLocation sheet, int x, int y,
                               int w, int h, int u, int v, int tileW, int tileH) {
        int drawX = x;
        for (IntIterator columns = slices(w, tileW); columns.hasNext(); ) {
            int columnW = columns.nextInt();
            int uInset = (tileW - columnW) / 2;
            int drawY = y;
            for (IntIterator rows = slices(h, tileH); rows.hasNext(); ) {
                int rowH = rows.nextInt();
                int vInset = (tileH - rowH) / 2;
                graphics.blit(sheet, drawX, drawY, u + uInset, v + vInset, columnW, rowH, SHEET, SHEET);
                drawY += rowH;
            }
            drawX += columnW;
        }
    }

    private static IntIterator slices(int length, int tile) {
        return new Divisor(length, Mth.positiveCeilDiv(length, tile));
    }

    // --- panel.png ---------------------------------------------------------------------------

    /** The outer window frame every full screen sits in. */
    public static final Sprite WINDOW = Sprite.panel(0, 0, 48, 48, 8, 8);
    /** The inset dark area content scrolls inside. Light text is legible on it; grey would not be. */
    public static final Sprite WELL = Sprite.panel(48, 0, 48, 48, 6, 6);
    public static final Sprite CARD = Sprite.panel(96, 0, 48, 48, 5, 5);
    /** A quest whose objectives are all satisfied — the same green the log and HUD already use. */
    public static final Sprite CARD_READY = Sprite.panel(144, 0, 48, 48, 5, 5);
    public static final Sprite CARD_HOVER = Sprite.panel(192, 0, 48, 48, 5, 5);

    /** Translucent tracker background. The alpha is baked in, so the overlay needs no colour maths. */
    public static final Sprite HUD = Sprite.panel(0, 48, 48, 48, 6, 6);
    public static final Sprite BAND_HEADER = Sprite.panel(48, 48, 48, 24, 6, 6);
    public static final Sprite BAND_FOOTER = Sprite.panel(48, 72, 48, 24, 6, 6);
    public static final Sprite TAB_SELECTED = Sprite.panel(96, 48, 32, 24, 6, 6);
    public static final Sprite TAB_UNSELECTED = Sprite.panel(128, 48, 32, 24, 6, 6);
    public static final Sprite TAB_HOVER = Sprite.panel(160, 48, 32, 24, 6, 6);
    /** Pill behind a difficulty or category label. */
    public static final Sprite BADGE = Sprite.panel(192, 48, 32, 16, 5, 5);
    /** 18×18, the size of every vanilla slot, so a reward item sits in it at the expected offset. */
    public static final Sprite SLOT = Sprite.panel(224, 48, 18, 18, 0, 0);
    public static final Sprite DIVIDER = Sprite.panel(192, 66, 48, 3, 2, 1);

    public static final Sprite BUTTON = Sprite.panel(0, 96, 80, 20, 6, 6);
    public static final Sprite BUTTON_HOVER = Sprite.panel(80, 96, 80, 20, 6, 6);
    public static final Sprite BUTTON_DISABLED = Sprite.panel(160, 96, 80, 20, 6, 6);

    /**
     * The compact button family exists for the quest log's 60×12 Abandon button. Vanilla nine-slices
     * a 200×20 sprite with 4px vertical slices, so a 12px-tall vanilla button renders visibly
     * squashed; these are drawn to work at that height.
     */
    public static final Sprite BUTTON_COMPACT = Sprite.panel(0, 116, 64, 12, 4, 4);
    public static final Sprite BUTTON_COMPACT_HOVER = Sprite.panel(64, 116, 64, 12, 4, 4);
    public static final Sprite BUTTON_COMPACT_DISABLED = Sprite.panel(128, 116, 64, 12, 4, 4);

    public static final Sprite BAR_TRACK = Sprite.panel(0, 128, 64, 6, 3, 2);
    /** Objective and quest progress. */
    public static final Sprite BAR_GREEN = Sprite.panel(0, 134, 64, 6, 3, 2);
    /** Your own share of a shared project total, over the green of everybody's. */
    public static final Sprite BAR_BLUE = Sprite.panel(0, 140, 64, 6, 3, 2);
    /** Time running out. */
    public static final Sprite BAR_AMBER = Sprite.panel(0, 146, 64, 6, 3, 2);

    public static final Sprite SCROLL_TRACK = Sprite.panel(64, 128, 6, 32, 2, 3);
    public static final Sprite SCROLL_THUMB = Sprite.panel(70, 128, 6, 32, 2, 3);
    public static final Sprite SCROLL_THUMB_HOVER = Sprite.panel(76, 128, 6, 32, 2, 3);
    public static final Sprite SCROLL_THUMB_DRAG = Sprite.panel(82, 128, 6, 32, 2, 3);

    // --- icons.png, row 0: what a thing is ------------------------------------------------------

    public static final Sprite ICON_QUEST = Sprite.icon(0, 0);
    public static final Sprite ICON_CHAIN = Sprite.icon(1, 0);
    public static final Sprite ICON_PROJECT = Sprite.icon(2, 0);
    public static final Sprite ICON_SITUATION = Sprite.icon(3, 0);
    public static final Sprite ICON_REPUTATION = Sprite.icon(4, 0);
    public static final Sprite ICON_TITLE = Sprite.icon(5, 0);
    public static final Sprite ICON_VILLAGE = Sprite.icon(6, 0);
    public static final Sprite ICON_FAMILY = Sprite.icon(7, 0);
    public static final Sprite ICON_CLOCK = Sprite.icon(8, 0);
    public static final Sprite ICON_COMPASS = Sprite.icon(9, 0);
    public static final Sprite ICON_DISTANCE = Sprite.icon(10, 0);
    public static final Sprite ICON_DANGER = Sprite.icon(11, 0);
    public static final Sprite ICON_CHECK = Sprite.icon(12, 0);
    public static final Sprite ICON_CROSS = Sprite.icon(13, 0);
    public static final Sprite ICON_PAUSE = Sprite.icon(14, 0);
    public static final Sprite ICON_DOT = Sprite.icon(15, 0);

    // --- icons.png, row 1: state and value -------------------------------------------------------

    public static final Sprite ICON_HEART_FULL = Sprite.icon(0, 1);
    public static final Sprite ICON_HEART_HALF = Sprite.icon(1, 1);
    public static final Sprite ICON_HEART_EMPTY = Sprite.icon(2, 1);
    public static final Sprite ICON_OBJ_PENDING = Sprite.icon(3, 1);
    public static final Sprite ICON_OBJ_DONE = Sprite.icon(4, 1);
    public static final Sprite ICON_OBJ_FAILED = Sprite.icon(5, 1);
    /** An objective waiting on a mod that is not installed — not failure, and not completion. */
    public static final Sprite ICON_OBJ_SUSPENDED = Sprite.icon(6, 1);
    public static final Sprite ICON_PIP_EASY = Sprite.icon(7, 1);
    public static final Sprite ICON_PIP_MEDIUM = Sprite.icon(8, 1);
    public static final Sprite ICON_PIP_HARD = Sprite.icon(9, 1);
    public static final Sprite ICON_STAR = Sprite.icon(10, 1);
    public static final Sprite ICON_COIN = Sprite.icon(11, 1);
    public static final Sprite ICON_XP = Sprite.icon(12, 1);
    public static final Sprite ICON_GIFT = Sprite.icon(13, 1);
    public static final Sprite ICON_SCROLL = Sprite.icon(14, 1);
    public static final Sprite ICON_BOOK = Sprite.icon(15, 1);

    // --- icons.png, row 2: professions -----------------------------------------------------------

    public static final Sprite ICON_PROF_FARMER = Sprite.icon(0, 2);
    public static final Sprite ICON_PROF_FISHERMAN = Sprite.icon(1, 2);
    public static final Sprite ICON_PROF_SHEPHERD = Sprite.icon(2, 2);
    public static final Sprite ICON_PROF_FLETCHER = Sprite.icon(3, 2);
    public static final Sprite ICON_PROF_LIBRARIAN = Sprite.icon(4, 2);
    public static final Sprite ICON_PROF_CARTOGRAPHER = Sprite.icon(5, 2);
    public static final Sprite ICON_PROF_CLERIC = Sprite.icon(6, 2);
    public static final Sprite ICON_PROF_ARMORER = Sprite.icon(7, 2);
    public static final Sprite ICON_PROF_WEAPONSMITH = Sprite.icon(8, 2);
    public static final Sprite ICON_PROF_TOOLSMITH = Sprite.icon(9, 2);
    public static final Sprite ICON_PROF_BUTCHER = Sprite.icon(10, 2);
    public static final Sprite ICON_PROF_LEATHERWORKER = Sprite.icon(11, 2);
    public static final Sprite ICON_PROF_MASON = Sprite.icon(12, 2);
    public static final Sprite ICON_PROF_GUARD = Sprite.icon(13, 2);
    public static final Sprite ICON_PROF_ARCHER = Sprite.icon(14, 2);
    /** The fallback: a villager whose profession the mod has no glyph for, including none at all. */
    public static final Sprite ICON_PROF_VILLAGER = Sprite.icon(15, 2);
}
